### ISSUE TITLE
Mod does not work on 1.21.4.

### ISSUE THREAD

**Issue by Caisenn** [ianaduarte/mydriasis#2]
There is no effects, but there is on 1.21.1 tho. I had only that mod (and fabric api obviously).

Info from logs from 1.21.4, that isn't present in 1.21.1:
Removed resource pack mydriasis:lightmap_patch from options because it is no longer compatible

**Comment by ianaduarte** [comment]
yeah my bad i had an incorrect `pack_format` set.

https://modrinth.com/mod/mydriasis/version/bjGKdDjk
